import Head from 'next/head'
import Image from 'next/image'
import Code from '../components/Code/Code'
import Discover from '../components/Discover/Discover'
import Footer from '../components/Footer/Footer'
import Form from '../components/Form/Form'
import Hero from '../components/Hero/Hero'
import Navbar from '../components/Navbar/Navbar'
import Offers from '../components/Offers/Offers'
import Patients from '../components/Patients/Patients'
import Payment from '../components/Payment/Payment'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Red Paws Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar />
    <br />
    <br />
    <Hero />
    <br />
    <Discover />
    <br />
    <br />
    <Patients />
    <br />
    <br /> 
    <br />
    <br /> 
    <Payment />
    <br />
    <br />
    <Code />
    <br /> 
    <br />
    <br />
    <br />
    <Form />
    <br /> 
    <br />
    <br /> 
    <br />
    <Offers />
    <br />
    <br />
    <br />
    <br />
    <Footer />
    </div>
  )
}
